pull_request_rules:
  - name: automatic merge when GitHub branch protection passes on master
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
    actions:
      merge:
        method: merge
